### ISSUE TITLE
Small feature request

### ISSUE THREAD

**Issue by ghost** [neXyon/audionodes#2]
Hello everyone.

This project is about adding 3 modules in AudioNodes from NeXyon.
The modules are:
 - Note input (uses ABC Notation in the *NON* extended form) - Used to alter an Oscillator input frequency
 - Node input Sequencer - Used to put Node inputs in order and play them
 - Module index number - Used to refer to a Note input from the Oscillator it gets connected to. Same thing as specifying which instrument will play the specified notes.

E.G.: let's pretend i have a kick, i call it KS.
Now i add a bass, index BS.

Then, the KS ABC content should be "cccc" (four C notes, 1/4 each)
And the BS will contain "CcCcCcCc" (eight notes, 1/8 each - transposes one octave)

In the sequencer, I'll write "KS, KS BS, BS"
Comma is used to split bars, more indices mean play simultaneously, time shifting (*NOT* stretching, neither transposing) could be described as +/- ev/be/ba (single event, beat, bar) and a number.

Note: the Note input shouldn't be directly connected to the osc, in fact it and should have no i/o sokets, while the sequencer should only output to the Note input.
This means, in the Note input node, I'll have to specify the Module index number(s) to plug to the Oscillator to.

**Comment by mrrm92** [comment]
P.S.: The NI shouldn't be directly connected to the osc.
It and should have no i/o sokets, while the sequencer should only output to the play node.
The sequencer syntax should include the module(s) to play the note with, so a 3rd node, containing a serial module index, should be added too, let's call this mi.

So, if i want to compose the kick above, i have to define a synth and assign it a label (let's call this ks).
In tje NI i write cccc, in the sequencer i'll write ks+mi

**Comment by neXyon** [comment]
What you're asking for is far from a small feature... Since this is anyway only a demo that has no real use, I'll not keep developing it. Sorry.
