### ISSUE TITLE
Can't get AudioNodes editor - Nodes doesn't exist in example file

### ISSUE THREAD

**Issue by anonimo82** [neXyon/audionodes#6]
Hello @neXyon 
Unfortunately, I get errors when opening your example file, and despite your addon loads fine, with no errors, I can't have nodes in the example file you provided.
Here is a screenshot: 
![nodes](https://github.com/neXyon/audionodes/assets/38261009/65794d8b-16f0-4af5-bc95-080d0997a144)

Please, help me. I'd really like to try your nodes =)

**Comment by neXyon** [comment]
I pushed a fix, should work now! Please reopen if it still doesn't.

**Comment by anonimo82** [comment]
Yes, it now works, thanks a lot.
